Inform synchronize module about community.docker collection
ansible-collections/ansible.posix pull request #144
Opened 2021-02-28 22:36 UTC by tadeboro

##### SUMMARY
The synchronize action plugin has a built-in list of connection plugins that it knows how to handle.

One of those connection plugins is the docker connection plugin. And because the docker content has been moved around quite a lot, the docker connection plugin has quite a few names:

 - docker in Ansible 2.9,
 - community.general.docker for community.general < 2.0.0, and
 - community.docker.docker since a few months ago.

And while the synchronize module already knew about the first two names, the last one was still missing. This commit fixes that omission and adds a third name into the mix.

Fixes #132 

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
synchronize

2021-03-01 06:21 UTC, Akasurde requested changes

2021-03-01 06:21 UTC, Akasurde commented on plugins/action/synchronize.py
> -        if self._remote_transport not in ['docker', 'community.general.docker', 'buildah', 'containers.podman.buildah'] and user:
Could you please add a changelog entry for this change? rest LGTM

2021-03-01 06:22 UTC, Akasurde commented
CI failures are known. PR https://github.com/ansible/ansible/pull/73609 will resolve the error.

2021-03-01 06:23 UTC, Akasurde commented
cc @maxamillion @felixfontein

2021-03-01 06:40 UTC, felixfontein commented
:+1: for this change!

2021-03-01 08:30 UTC, tadeboro commented
I added a changelog fragment. My plan was to add it once I know things are green, but I guess this might take a while to become reality ;)

2021-03-01 11:32 UTC, felixfontein commented on changelogs/fragments/144_add_community_docker_connection_plugin_alias.yml
> +    transports (https://github.com/ansible-collections/ansible.posix/issues/132)
```suggestion
  - synchronize - add ``community.docker.docker`` to the list of supported
    transports (https://github.com/ansible-collections/ansible.posix/issues/132).
```

2021-03-02 07:46 UTC, felixfontein approved these changes

2021-03-02 15:31 UTC, Akasurde commented
recheck

2021-03-02 19:29 UTC, felixfontein commented on plugins/action/synchronize.py
> +        if self._remote_transport in ['docker', 'community.general.docker', 'community.docker.docker', 'buildah', 'containers.podman.buildah'] and not use_delegate:
This line is too long according to Zuul:
```
2021-03-02 15:56:10.113840 | centos-8 | ERROR: plugins/action/synchronize.py:392:161: E501: line too long (164 > 160 characters)
```
(https://e95bd11f717195a90d9d-c7dcb72ad68df77a0c76e81c84cbc136.ssl.cf2.rackcdn.com/144/a5e46017e973c4c91dfec1b0414e20335c677d0e/check/ansible-test-sanity-docker-stable-2.10/cc43b2f/job-output.html#l9902)

2021-03-05 12:14 UTC, felixfontein approved these changes

2021-03-05 13:58 UTC, Akasurde commented
recheck

2021-03-05 14:00 UTC, Andersson007 commented
@Akasurde i think we should wait until https://github.com/ansible-collections/ansible.posix/pull/147 merged

2021-03-05 14:08 UTC, Akasurde commented
> @Akasurde i think we should wait until #147 merged

👍🏼

2021-03-05 16:18 UTC, Andersson007 commented
the tests passed now

2021-03-05 16:19 UTC, Andersson007 commented
after this merged, i can release the collection next week (if nobody disagrees)

2021-03-05 17:49 UTC, merged