Fix requires firewalld version in comments for permanent parameter.
ansible-collections/ansible.posix pull request #233
Opened 2021-07-27 07:39 UTC by piotrtrojanowski-dev

##### SUMMARY
Version of firewalled seems to be wrong. 3.0.9 version of that package does not exist.
The latest release of firewalled: https://github.com/firewalld/firewalld/releases

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
ansible.posix.firewalld

```

2021-07-27 08:45 UTC, saito-hideki requested changes
Also, could you create a new changelog fragments file to describe this fix? You can add a new file like `213-fix-wrong-firewalld-version-info.yml` under https://github.com/piotrtrojanowski-dev/ansible.posix/tree/patch-2/changelogs/fragments/

And it should contain like below short description of this change:
```
---
trivial:
  - firewalld - fix wrong version number in the module document.
```

You can see more details here: https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment

Update information for the release of the new version is generated from this fragments file. So once you added the changelog fragments file, I'll approve this PR.

thanks! :)

2021-07-27 08:45 UTC, saito-hideki commented on plugins/modules/firewalld.py
> +      - As of Ansible 2.3, permanent operations can operate on firewalld configs when it is not running (requires firewalld >= 0.3.9).
Thank you for fixing this. Looks good to me :)

2021-08-07 04:36 UTC, saito-hideki commented
Closing and re-opening for CI trigger.

2021-08-07 04:47 UTC, saito-hideki commented
Closing and re-opening for CI trigger.

2021-08-07 05:34 UTC, saito-hideki approved these changes
I have added changelog fragment file. Thanks!

2021-08-09 13:27 UTC, saito-hideki commented
@Akasurde @Andersson007
If it is possible, can you guys review for this PR?

2021-08-10 05:58 UTC, Andersson007 approved these changes

2021-08-10 06:42 UTC, merged