Fix callback output to align header with roles, tasks and play RECAP
ansible-collections/ansible.posix pull request #387
Opened 2022-09-20 21:46 UTC by ansiblejunky

##### SUMMARY
All three callback plugins (timer, roles, tasks) do not produce headers in the output that align with how we do "PLAY RECAP *********" that is generated by the "default" output callback. So these changes are provided to align the callback plugins and have a clean output that is much more readable.

Note, the asterisks are generated just as how they are for "PLAY RECAP", where it extends to the end of the terminal window.

I am considering this as a "bug" in that the output was never aligned, instead of a feature since this does not provide any new feature per-se. 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ansible.posix.timer
ansible.posix.profile_tasks
ansible.posix.profile_roles

##### ADDITIONAL INFORMATION

The new output is shown below. You can see the headers are now all the same and broken down by PLAY, ROLE, TASKS, and PLAYBOOK RECAP.

```paste below
PLAY RECAP ***************************************************************************************************************************************************************************************
localhost                  : ok=14   changed=2    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

ROLE RECAP ***************************************************************************************************************************************************************************************
awx.awx.subscriptions --------------------------------------------------- 4.81s
users ------------------------------------------------------------------- 2.89s
labels ------------------------------------------------------------------ 2.86s
settings ---------------------------------------------------------------- 2.46s
credential_types -------------------------------------------------------- 2.27s
organizations ----------------------------------------------------------- 2.21s
teams ------------------------------------------------------------------- 2.21s
awx.awx.license --------------------------------------------------------- 1.49s
dispatch ---------------------------------------------------------------- 0.58s
credentials ------------------------------------------------------------- 0.03s
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
total ------------------------------------------------------------------ 21.80s

TASKS RECAP **************************************************************************************************************************************************************************************
Get subscriptions with a filter ----------------------------------------------------------------------------------------------------------------------------------------------------------- 4.81s
redhat_cop.controller_configuration.users : Configure Users | Wait for finish the Users creation ------------------------------------------------------------------------------------------ 1.93s
redhat_cop.controller_configuration.labels : Configure Labels | Wait for finish the Label creation ---------------------------------------------------------------------------------------- 1.91s
redhat_cop.controller_configuration.settings : Configure Settings | Wait for finish the Settings creation --------------------------------------------------------------------------------- 1.75s
redhat_cop.controller_configuration.teams : Configure Teams | Wait for finish the Teams creation ------------------------------------------------------------------------------------------ 1.63s
redhat_cop.controller_configuration.organizations : Configure Controller Organizations | Wait for finish the organization creation -------------------------------------------------------- 1.62s
Attach to a pool -------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 1.49s
redhat_cop.controller_configuration.credential_types : Add Credential Types --------------------------------------------------------------------------------------------------------------- 1.32s
redhat_cop.controller_configuration.users : Add controller user --------------------------------------------------------------------------------------------------------------------------- 0.96s
redhat_cop.controller_configuration.labels : Add a label to Controller -------------------------------------------------------------------------------------------------------------------- 0.95s
redhat_cop.controller_configuration.credential_types : Configure Controller Credential Types | Wait for finish the credential types creation ---------------------------------------------- 0.94s
redhat_cop.controller_configuration.settings : Update Ansible Controller Settings from dictionary or list of dictionaries ----------------------------------------------------------------- 0.70s
redhat_cop.controller_configuration.organizations : Add organizations --------------------------------------------------------------------------------------------------------------------- 0.59s
redhat_cop.controller_configuration.teams : Create Ansible Controller Team ---------------------------------------------------------------------------------------------------------------- 0.58s
Run redhat_cop.controller_configuration.{{ __role.role }} role ---------------------------------------------------------------------------------------------------------------------------- 0.58s
redhat_cop.controller_configuration.credentials : Add Credentials ------------------------------------------------------------------------------------------------------------------------- 0.03s

PLAYBOOK RECAP ***********************************************************************************************************************************************************************************
Playbook run took 0 days, 0 hours, 0 minutes, 21 seconds

```

2022-09-20 23:33 UTC, sean-m-sullivan commented
2nded on this, would have loved the headers 3 years ago when using this for figuring out scaling and forks.

2023-03-24 08:17 UTC, saito-hideki requested changes
Thank you for this PR. Those fixes are pretty reasonable.
However, some CI tests have failed now. So there are two change requests here to address the CI problems:

1. if it is possible, can you rebase this PR?
2. Also, could you add a changelog fragment file according to https://docs.ansible.com/ansible/latest/community/development_process.html#creating-changelog-fragments ?

2023-04-07 03:21 UTC, saito-hideki commented on plugins/callback/profile_roles.py
> +
To pass the sanity test, you need to remove the whitespace at the end of the line.

2023-04-07 03:23 UTC, saito-hideki commented on plugins/callback/profile_tasks.py
> +
To pass the sanity test, you need to remove the whitespace at the end of the line.

2023-04-07 03:26 UTC, saito-hideki requested changes
Please add the changelog fragment file and remove the whitespace at EOF line. Once you fix them, I will approve this PR :)

2024-10-02 06:31 UTC, saito-hideki approved these changes
@ansiblejunky 
I've added a fragment file, so I will merge it after all CI tests are passed.
Thanks for your contribution! :)

2024-10-02 06:44 UTC, merged