json[l] callback: add parameter to set JSON prettyprint indent level
ansible-collections/ansible.posix pull request #441
Opened 2023-04-08 12:14 UTC by jsquyres

##### SUMMARY

Add `ANSIBLE_JSON_INDENT` parameter to both the `json` and `jsonl` callback plugins.  The default values are different between the two modules to maintain their existing behavior:

* json: indent==4, causing a prettyprint output
* jsonl: indent==0, causing a 1-line output

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
- ansible.posix.json
- ansible.posix.jsonl

##### ADDITIONAL INFORMATION
One specific use-case that is enabled by this feature: if a user chooses to use the `jsonl` plugin so that they still get output at the end of each task (vs. only at the end of the play), they may also want human-readable output so that they can monitor the status of their play.  For example, setting the `jsonl` indent level to 4 gives a) output at the end of each task, and b) making that output be both machine readable and human readable.

Using this trivial playbook shows the change:

```yaml
- hosts: localhost
  gather_facts: false
  tasks:
    - name: hello, world
      debug:
        msg: hello, world
```

When using the `jsonl` callback, here's what one JSON emit looks like before the change:

```json
{"_event":"v2_playbook_on_play_start","_timestamp":"2023-04-08T12:11:48.001806Z","play":{"duration":{"start":"2023-04-08T12:11:48.001383Z"},"id":"acde4800-1122-f32c-94c3-000000000001","name":"localhost"},"tasks":[]}
```

After the change, setting `ANSIBLE_JSON_INDENT` to 4, the same output looks like this:

```json
{
    "_event":"v2_playbook_on_play_start",
    "_timestamp":"2023-04-08T12:12:47.787516Z",
    "play":{
        "duration":{
            "start":"2023-04-08T12:12:47.787164Z"
        },
        "id":"acde4800-1122-2946-e3e4-000000000001",
        "name":"localhost"
    },
    "tasks":[]
}
```

Both outputs are suitable for automated processes to parse the machine-readable output.  The second output has the benefit of being human readable.

2023-04-13 16:15 UTC, maxamillion requested changes
Need to preserve current behavior of callbacks.

2023-04-13 17:37 UTC, jsquyres commented on plugins/callback/json.py
> +        default: 4
I'm not sure I understand your comment.  Previously, in the `json` plugin, the indent was hard-coded a 4.  I just made this into a run-time parameter, but kept the default value the same (4).

Hence, the current behavior is preserved.

2023-04-13 17:38 UTC, jsquyres commented on plugins/callback/jsonl.py
> +        default: 0
> I don't use the jsonl callback, is printing to a single line the current behavior here?

Yes.

2023-04-17 12:59 UTC, jsquyres commented on plugins/callback/json.py
> +        default: 4
@maxamillion Ping.

2023-04-18 15:00 UTC, jsquyres commented
@maxamillion I updated the comment to remove the errant bit about unspecified, but the default behavior is still the same (i.e., it matches what the existing plugin already does).

2023-04-21 17:13 UTC, jsquyres commented
Greetings @maxamillion Can you please review again?  Thanks.

2023-04-27 19:07 UTC, jsquyres commented
Ping @maxamillion It's been over a week. Can you please re-review?  Thanks!

2023-04-27 20:28 UTC, maxamillion commented
@jsquyres apologies for the lag time! I'll get it reviewed, thank you for the reminder ping.

2023-04-27 20:31 UTC, maxamillion approved these changes
LGTM!

2023-04-27 20:32 UTC, maxamillion commented
Thank you again for the contribution, I've tagged it to merge. The bot will take it from here! :)

2023-04-27 20:52 UTC, merged