Docs: fix unclearence add example with reletive pathes #483
ansible-collections/ansible.posix pull request #490
Opened 2023-09-02 18:44 UTC by atom4git

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2023-09-05 14:59 UTC, goneri requested changes

2023-09-05 17:18 UTC, goneri requested changes
Could you also please fix the commit message.

2023-09-05 21:15 UTC, goneri requested changes

2023-09-05 21:15 UTC, goneri commented on plugins/modules/authorized_key.py
> -      - Alternate path to the authorized_keys file.
Please key the line

2023-09-05 21:15 UTC, goneri commented on plugins/modules/authorized_key.py
> -      - When unset, this value defaults to I(~/.ssh/authorized_keys).
You can remove this line, but you still need to mention the default path somewhere.

2023-09-05 21:15 UTC, goneri commented on plugins/modules/authorized_key.py
> +      - It's not necessary to set this key. The default value should be enough most of the time.
Please change that to `Most of the time. it's not necessary to set this key. The default value should just work.`. I'm afraid the previous sentence was not clear enough.

2023-09-05 22:26 UTC, goneri requested changes

2023-09-05 22:26 UTC, goneri commented on plugins/modules/authorized_key.py
> -      - When unset, this value defaults to I(~/.ssh/authorized_keys).
Thanks, you still need to mention that `I(~/.ssh/authorized_keys)` is the default value.

2023-09-06 20:14 UTC, goneri commented on plugins/modules/authorized_key.py
> +     - Use the path to your target authorized_keys if you need to explicitly point on it.
- The default value is the C(~/.ssh/authorized_keys) of the user specified in the P(user) parameter.

2023-09-07 20:20 UTC, goneri approved these changes
Thank you @atom4git for your patience and for taking the time to clarify the documentation <3.

2024-02-06 21:52 UTC, maxamillion commented
closing and re-opening to kick CI

2024-04-02 08:19 UTC, saito-hideki approved these changes
Thanks for the PR.
I rebased this PR and fixed the indentation in the document.

2024-04-02 08:44 UTC, merged